name: 'dartshelf'
version: 0.0.1
description: A minimal web server using the shelf package.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.13.0'
  shelf: '>=0.5.5 <0.6.0'
  http: any
  xml: ">=2.0.0 <3.0.0"
  quiver: '>=0.21.0<0.22.0'