name: 'dartshelf'
version: 0.0.1
description: A minimal web server using the shelf package.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  shelf: '^0.6.0'
  shelf_route: "^0.12.0"
  http: any
  xml: ">=2.0.0 <3.0.0"
  #timezone: ">=0.2.5 <0.3.0"